### PR TITLE
feat(autocomplete) in view

### PR DESCRIPTION
**Pull request by hiaux0**
## What was done

- fix instellisense in view template
  path given by vscode and `aureliaComponent` had a different format

- provide completion inside `${}`

out

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Tears of joy 😂 

Amazing work you've been doing @hiaux0 I wonder if you would be interested in joining our core team, partnering with @eriklieben to focus on tooling. No pressure. If that sounds interesting, let me know and we can discuss further.

**Comment by 3cp** [comment]
Hey @EisenbergEffect , job offer is supposed to be private, especially the ones with no pay 😆

**Comment by EisenbergEffect** [comment]
I just got pretty excited. Us project leaders go nuts for animated gifs 🤣

**Comment by hiaux0** [comment]
>  for animated gifs

The worlds needs less cat gifs and more code-demonstration-gifs!

> I wonder if you would be interested in joining our core team, partnering with @eriklieben to focus on tooling.

I have sent you a message on discourse :)

**Pull request merged**
